apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: k8-service
  labels: 
    app: k8-service
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      task: two
  template:
    metadata:
      labels:
        task: two
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 81